---
title: "Team Cousin Analytics"
sidebar: false 
---

This is our project webpage.

Please stay tuned to follow our project activities.

This is our template.

# Team Members

1.  [Emir Gök](https://emu-hacettepe-analytics.github.io/emu430-fall2024-emirrgok/)

2.  [Vehbi Enis Üçer](https://emu-hacettepe-analytics.github.io/emu430-fall2024-enisucer/)

3.  [Berk Bayar](https://emu-hacettepe-analytics.github.io/emu430-fall2024-berkbyr/)

4.  [Mustafa Melih Dağ](https://emu-hacettepe-analytics.github.io/emu430-fall2024-melihdag1/)

5.  [Ulaş Utku Bedel](https://emu-hacettepe-analytics.github.io/emu430-fall2024-ulasutkubedel)

# Our Project

**Title:** `Analysis of Key Performance Indicators and Squad Market Values Impacting Rankings in Turkey’s Süper Lig: A Focus on Shooting Accuracy, Possession, and Goals (2015-2024)`

**Description:**\
This project analyzes how key performance indicators—such as average shots, average shots on target, average ball possession, average goals scored, average goals conceded, squad market values, and team rankings—have influenced the performance of Turkey's top football teams in the Süper Lig over the past 9 seasons (2015-2024). The study examines the relationships between offensive and defensive metrics, market value of players, and their direct impact on league rankings. By incorporating squad market values, the project explores how a team's financial strength and player quality contribute to overall success. Key visualizations, including trend analysis, bar chart races, and correlation graphs, illustrate the effect of these variables on team performance. The analysis aims to uncover patterns of success, identify underperforming areas, and provide actionable insights into the factors most strongly determining a team’s position in the league standings.

# Video

<video controls width="400">

<source src="video.mp4" type="video/mp4">

</video>

# Data Set

[Turkish Super League Stats for top 4 teams, The period between 2015-2016 and 2023-2024](./superligstats.xlsx)

# Key Takeaways

-   **Most Important Factors**: **Goals scored** and **goals conceded** are the most important factors for determining rankings. A strong attacking ability (scoring goals) combined with a solid defense (conceding fewer goals) are the key to maintaining or improving a team’s league position.

-   **Secondary Factors**: **Ball possession** and **squad market value** have a secondary role. While they contribute to team performance, they do not directly drive rankings as effectively as offensive and defensive performance. Possession might help control the tempo of a game, and squad market value can aid in acquiring top talent, but these factors are less directly linked to achieving top rankings in the league.
